# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65f7382d87efcffedbd4b0c30d1a6020f69db0c8e492c5ca57670d2e6881e098774b65d64abce9f1ce39e8e2c6b7e1d368e198c1596431789f22cd805562ee5e

test:
  secret_key_base: 109aab6ead47a182a704438fe202488d89002515768324b2a8c76e87f139decb81d0352a3770e7c72cd0cfbf3e2e97bac853eb2c8db055ddb157b795c3749b5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
